config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'dashboard#dashboard', as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :categories

  resources :products do
    collection do
      post :search
    end
    resources :product_sales_units, shallow: true, except: %i[index show]
  end

  resources :customers do
    collection do
      post :search
    end
  end

  resources :employees do
    collection do
      post :search
    end
  end

  resources :suppliers do
    collection do
      post :search
    end
  end

  resources :sales_units, except: :show
  resources :sales

  post '/new-category', action: :create_new_category, controller: 'products', as: 'new_product_category'
  match '/404', to: 'errors#not_found', via: :all
  post '/items/search', to: 'sales#search', as: 'items_search'
end

app/views/shared/_page_header.erb
<div class='page-header'>
  <%= link_to '<i class="bi bi-arrow-left h3"></i>'.html_safe, 'javascript:history.back()' unless title == 'Home'%>
  <span class='h3'><%= title%></span>
</div>

app/views/shared/_page_header.html.erb
<div class='page-header'>
  <%= link_to '<i class="bi bi-arrow-left h3"></i>'.html_safe, 'javascript:history.back()' unless title == 'Home'%>
  <span class='h3'><%= title%></span>
</div>

app/views/shared/_parties_search_form.html.erb
<div class= 'm-4'>
  <%= form_with url: url, local: false,  method: :post do |form|%>
    <div class = 'search-form'>
      <%= form.search_field :search, placeholder: 'Search by Name', class: 'search-input', oninput: "this.form.requestSubmit()" %>
    </div>
  <% end %>
</div>

app/views/shared/_product.erb
<div class='d-flex product-body'>
  <div class='w-100'>
    <strong><%= product.name.camelize %></strong>
    <div>SKU: <%= product.code %></div>
  </div>
  <div class='w-100'><%= product.category&.name&.camelize || 'Others'%></div>
  <div class='w-100'><%= stock_status(product.quantity) %></div>
  <div class='w-100'>
    <% if product.avatar.attached?%>
      <%= image_tag product.avatar, class: 'product-img'%>
    <% end%>
  </div>
</div>

<div class='product-expand d-none new-product-form'>
  <div class='d-flex justify-content-end' id='cros-expand'>
    <i class="bi bi-x-lg"></i>
  </div>
  <%= form_for(product, remote: true) do |f|%>
    <div class='d-flex mt-2'>
      <div class='w-100 mb-3'>
        <label for='code'>Product Code</label>
        <%= f.text_field :code, autofocus: true, placeholder: 'Enter Product Code', class: 'form-control', required: true %>
      </div>
      <div class='w-100 mb-3 left-margin'>
        <label for='name'>Product name</label>
      <%= f.text_field :name, placeholder: 'Enter Product Name', class: 'form-control', required: true %>
      </div>
    </div>
    <div class='d-flex'>
      <div class='w-100 mb-3'>
        <%= f.label :description %>
        <%= f.text_field :description, placeholder: 'Enter Product Details', class: 'form-control' %>
      </div>
      <div class='w-100 mb-3 left-margin product-category-select'>
        <%= f.label :category %>
        <%= f.collection_select :category_id, @categories, :id, :name%>
      </div>
    </div>
    <div class='d-flex mt-2'>
      <div class='w-100 mb-3'>
        <%= f.label :quantity, 'Stock' %>
        <%= f.number_field :quantity, placeholder: 'Enter Product Stock', class: 'form-control', min: 0 %>
      </div>
      <div class='w-100 mb-3 left-margin'>
        <%= f.label :avatar, 'Update Image' %>
        <%= f.file_field :avatar,  class: 'form-control', direct_upload: true, accept: "image/*" %>
      </div>
    </div>
    <div class='d-flex'>
      <div class='w-100 text-center'>
        <%= f.submit 'Update Product', class: 'btn btn-success', data: { confirm: 'Are you sure? you want to update this product?' } %>
      </div>
      <div class='w-100 text-center'>
        <%= link_to '<i class="bi bi-trash3"></i>'.html_safe, product_path(product.id), method: :delete, data: { confirm: 'Are you sure? you want to delete this product?' }, class: 'btn btn-outline-danger'%>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_products_listing.erb
<div class='d-flex my-3'>
  <div class='w-100'>
    <h4>Total Products: <%= @pagy.count%></h4>
  </div>
  <div class='w-50'>
    <%= link_to '<i class="bi bi-plus-lg"></i> Add Product'.html_safe, new_product_path, class: 'btn btn-success'%>
  </div>
</div>

<%= render partial: 'shared/product', collection: @products%>

<div class='d-flex justify-content-center mt-2'>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/shared/_products_listing.html.erb
<div class='d-flex my-3'>
  <div class='w-100'>
    <h4>Total Products: <%= @pagy.count%></h4>
  </div>
  <div class='w-50'>
    <%= link_to '<i class="bi bi-plus-lg"></i> Add Product'.html_safe, new_product_path, class: 'btn btn-success'%>
  </div>
</div>

<%= render partial: 'shared/product', collection: @products%>

<div class='d-flex justify-content-center mt-2'>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/shared/_side_bar.erb
<div class="d-flex flex-column flex-shrink-0 p-3 side-bar">
    <div class="logo">
      <i class="bi bi-shop-window"></i>
      <strong class="h5">Point Of Sale System</strong>
    </div>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <%= link_to '<i class="bi bi-house-door icon-style"></i>Home'.html_safe, root_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'home'}" %>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <i class="bi bi-speedometer2 icon-style"></i>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <i class="bi bi-cart4 icon-style"></i>
          Sale
        </a>
      </li>
      <li>
        <a type="button" class="sidebar-submenu nav-link link-dark">
          <i class="bi bi-basket2-fill icon-style"></i>Products
          <i class="bi bi-caret-down-fill"></i>
        </a>
        <div class="sidebar-submenu-container" display_products_submenu = "<%= hide_products_submenu(controller.controller_name) %>">
          <%= link_to 'Products List', products_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'products'}" %>
          <%= link_to 'Categories', categories_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'categories'}" %>
        </div>
      </li>
      <li>
        <a type="button" class="sidebar-submenu nav-link link-dark">
          <i class="bi bi-people-fill icon-style"></i>Parties
          <i class="bi bi-caret-down-fill"></i>
        </a>
        <div class="sidebar-submenu-container" display_parties_submenu = "<%= hide_parties_submenu(controller.controller_name) %>">
          <%= link_to 'Customers', customers_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'customers'}" %>
          <%= link_to 'Suppliers', suppliers_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'suppliers'}" %>
          <%= link_to 'Employees', employees_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'employees'}" %>
        </div>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <i class="bi bi-graph-up-arrow icon-style"></i>
          Reports
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" style="color: #0d6efd" class="admin-dropdown dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-person-circle"></i>
        <strong>Admin</strong>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
        <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
      </ul>
    </div>
  </div>

app/views/shared/_side_bar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 side-bar">
    <div class="logo">
      <i class="bi bi-shop-window"></i>
      <strong class="h5">Point Of Sale System</strong>
    </div>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <%= link_to '<i class="bi bi-speedometer2 icon-style"></i> Dashboard'.html_safe, root_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'dashboard'}" %>
      </li>
      <li>
        <a type="button" class="sidebar-submenu nav-link link-dark">
          <i class="bi bi-cart4 icon-style"></i>Sale
          <i class="bi bi-caret-down-fill"></i>
        </a>
        <div class="sidebar-submenu-container" display_sales_submenu = "<%= hide_sales_submenu(controller.controller_name) %>">
          <%= link_to 'New Sale', new_sale_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'sales'}" %>
          <%= link_to 'Sales History', categories_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'sales history'}" %>
        </div>
      </li>
      <li>
        <a type="button" class="sidebar-submenu nav-link link-dark">
          <i class="bi bi-basket2-fill icon-style"></i>Items
          <i class="bi bi-caret-down-fill"></i>
        </a>
        <div class="sidebar-submenu-container" display_items_submenu = "<%= hide_items_submenu(controller.controller_name) %>">
          <%= link_to 'Products', products_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'products'}" %>
          <%= link_to 'Categories', categories_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'categories'}" %>
          <%= link_to 'Sales Units', sales_units_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'sales_units'}" %>
        </div>
      </li>
      <li>
        <a type="button" class="sidebar-submenu nav-link link-dark">
          <i class="bi bi-people-fill icon-style"></i>Parties
          <i class="bi bi-caret-down-fill"></i>
        </a>
        <div class="sidebar-submenu-container" display_parties_submenu = "<%= hide_parties_submenu(controller.controller_name) %>">
          <%= link_to 'Customers', customers_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'customers'}" %>
          <%= link_to 'Suppliers', suppliers_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'suppliers'}" %>
          <%= link_to 'Employees', employees_path, class: "nav-link link-dark #{'active' if controller.controller_name == 'employees'}" %>
        </div>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <i class="bi bi-graph-up-arrow icon-style"></i>
          Reports
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" style="color: #0d6efd" class="admin-dropdown dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-person-circle"></i>
        <strong>Admin</strong>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
        <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
      </ul>
    </div>
  </div>