config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'dashboard#dashboard', as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :categories

  resources :products do
    collection do
      post :search
    end
    resources :product_sales_units, shallow: true, except: %i[index show]
  end

  resources :customers do
    collection do
      post :search
    end
  end

  resources :employees do
    collection do
      post :search
    end
  end

  resources :suppliers do
    collection do
      post :search
    end
  end

  resources :sales_units, except: :show
  resources :sales

  post '/new-category', action: :create_new_category, controller: 'products', as: 'new_product_category'
  match '/404', to: 'errors#not_found', via: :all
  post '/items/search', to: 'sales#search', as: 'items_search'
end

app/models/product_sales_unit.rb
class ProductSalesUnit < ApplicationRecord
  AVAILABILITY_TYPES = {
    unavailable: 0,
    unlimited:   1,
    limited:     2
  }.freeze

  belongs_to :product
  belongs_to :sales_unit

  validates :sales_unit_id, uniqueness: { scope: %i[sales_unit_id product_id] }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :unit_price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  enum order_availability: AVAILABILITY_TYPES, _prefix: true

  scope :code_filter, ->(search) { joins(:product).where('products.code ILIKE ? ', "%#{search}%") }
  scope :name_filter, ->(search) { joins(:product).where('products.name ILIKE ? ', "%#{search}%") }

  def self.filter(params)
    code_filter(params).or(name_filter(params))
  end
end

app/controllers/product_sales_units_controller.rb
class ProductSalesUnitsController < ApplicationController
  before_action :find_sales_unit, only: %i[edit update destroy]
  def new
    @product = Product.find(params[:product_id])
    @sales_units = SalesUnit.all
    @product_sales_unit = @product.product_sales_units.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @product = Product.find(params[:product_id])
    @product_sales_unit = @product.product_sales_units.new(sales_unit_params)
    if @product_sales_unit.save
      flash[:notice] = 'Unit added Successfully!'
    else
      flash[:alert] = @product_sales_unit.errors.full_messages
    end
    redirect_to product_path(@product)
  end

  def edit
    @sales_units = SalesUnit.all
    respond_to do |format|
      format.js
    end
  end

  def update
    if @product_sales_unit.update(sales_unit_params)
      flash[:notice] = 'Unit updated Successfully!'
    else
      flash[:alert] = @product_sales_unit.errors.full_messages
    end
    redirect_to product_path(@product_sales_unit.product)
  end

  def destroy
    if @product_sales_unit.destroy
      flash[:notice] = 'Unit deleted Successfully!'
    else
      flash[:alert] = 'Unable to delete this Unit!'
    end
    redirect_to product_path(@product_sales_unit.product)
  end

  private

  def sales_unit_params
    params.require(:product_sales_unit)
          .permit(:sales_unit_id, :unit_price, :order_availability, :quantity)
  end

  def find_sales_unit
    @product_sales_unit = ProductSalesUnit.find(params[:id])
  end
end

app/views/shared/product_sales_unit/_unit.html.erb
<div class="card border-success mb-2">
  <div class="card-header text-center">
    <strong><%= unit.sales_unit.name%></strong> ( <strong><%= unit.sales_unit.abbreviation%></strong> )
  </div>
  <div class="card-body">
    <p class="card-text"><%= @product.description%></p>
    <p class="card-text"><strong>Unit Price: </strong><%= unit.unit_price %></p>
  </div>
  <div class='card-footer text-center'>
    <%= link_to '<i class="bi bi-pencil-square"></i> Edit'.html_safe, edit_product_sales_unit_path(unit), remote: true, class: 'btn m-1 btn-info'%>
    <%= link_to '<i class="bi bi-trash3"></i> Delete'.html_safe, product_sales_unit_path(unit), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn m-1 btn-danger'%>
  </div>
</div>

app/views/shared/product_sales_unit/_unit_form.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%="#{form_submit_btn_text(action)} Product Sales Unit"%></h4>
  <button type="button" class="close btn btn-light" data-dismiss="modal">X</button>
</div>
<%= form_for(@product_sales_unit, url: {action: action }) do |f| %>
  <div class="modal-body">
    <div class='d-flex'>
      <div class='w-100 mb-3'>
        <%= f.label :sales_unit %>
        <%= f.collection_select :sales_unit_id, @sales_units, :id, :name%>
      </div>
      <div class='w-100 mb-3 ms-1'>
        <%= f.label :unit_price %>
        <%= f.number_field :unit_price, placeholder: 'Enter Unit Price', class: 'form-control', required: true %>
      </div>
    </div>
    <div class='d-flex'>
      <div class='w-100 mb-3'>
        <%= f.label :order_availability %>
        <%= f.select :order_availability, ProductSalesUnit.order_availabilities.keys, class: 'form-control'%>
      </div>
      <div class='w-100 mb-3 ms-1'>
        <%= f.label :quantity %>
        <%= f.number_field :quantity, placeholder: 'Enter Unit Quantity', class: 'form-control', required: true %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <div class='d-flex'>
      <div class='w-100 text-center'>
        <%= f.submit "#{form_submit_btn_text(action)} Unit", class: 'btn btn-success'%>
      </div>
    </div>
  </div>
<% end %>