config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'dashboard#dashboard', as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :categories

  resources :products do
    collection do
      post :search
    end
    resources :product_sales_units, shallow: true, except: %i[index show]
  end

  resources :customers do
    collection do
      post :search
    end
  end

  resources :employees do
    collection do
      post :search
    end
  end

  resources :suppliers do
    collection do
      post :search
    end
  end

  resources :sales_units, except: :show
  resources :sales

  post '/new-category', action: :create_new_category, controller: 'products', as: 'new_product_category'
  match '/404', to: 'errors#not_found', via: :all
  post '/items/search', to: 'sales#search', as: 'items_search'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true

  default_scope -> { order(:created_at) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: %i[edit update destroy]
  def index
    @categories = Category.includes(:products)
  end

  def new
    @category = Category.new
    respond_to_js
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category added Successfully!'
    else
      flash[:alert] = @category.errors.full_messages
    end
    redirect_to categories_path
  end

  def edit
    respond_to_js
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category updated Successfully!'
    else
      flash[:alert] = @category.errors.full_messages
    end
    redirect_to categories_path
  end

  def destroy
    if @category.destroy
      flash[:notice] = 'Category deleted Successfully!'
    else
      flash[:alert] = @category.errors.full_messages
    end
    redirect_to categories_path
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit!
  end

  def respond_to_js
    respond_to do |format|
      format.js
    end
  end
end

app/views/categories/edit.js.erb
$("#new-category-modal-window").find(".modal-content").html("<%= escape_javascript(render partial: 'shared/category/new_category', locals: {action: 'update'} )%>");
$("#new-category-modal-window").modal('show');
$(".close").click(function(){
  $("#new-category-modal-window").modal('hide');
});

app/views/categories/index.html.erb
<%= render partial: 'shared/page_header', locals: {title: 'Categories'}%>

<div class='d-flex justify-content-end mx-3 mt-3'>
  <%= link_to '<i class="bi bi-plus-lg"></i> Add Category'.html_safe, new_category_path, remote: true, class: 'btn btn-success'%>
</div>

<div class='categories-list'>
  <%= render partial: 'shared/category/category', collection: @categories%>
</div>

<div id="new-category-modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/categories/new.js.erb
$("#new-category-modal-window").find(".modal-content").html("<%= escape_javascript(render partial: 'shared/category/new_category', locals: {action: 'create'} )%>");
$("#new-category-modal-window").modal('show');
$(".close").click(function(){
  $("#new-category-modal-window").modal('hide');
});